# Etapa de construcción usando Node 18.19.1
FROM node:18.19.1-alpine as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

# Etapa final usando la misma versión de Node 18.19.1
FROM node:18.19.1-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .
COPY --from=build /app/dist /app/dist

RUN yarn install --production

EXPOSE 5000

ENTRYPOINT [ "yarn", "start:prod" ]
